### PR TITLE
WIP - feat(master): trigger builds for the master branch

### LINKED ISSUE #40: Trigger master builds
I ported over all of our webhooks to use ci-gate, but it seems that master is no longer building. It'd be nice to also trigger master from this so we don't have to have two webhooks.

Wondering if you're open to doing this by default, or if we should have an environment variable to turn this on.

### PR DESCRIPTION
**Pull request by KevinGrandon**
This is a bit opinionated due to our workflow, but wanted to open this up in case you wanted to land or had feedback.

Fixes #40

### CODE REVIEW

**Comment by mvines** [comment]
Interesting.  I've found that the normal buildkite webhook for pushes is sufficient, I'm curious how your workflow prevents that from working?

**Comment by KevinGrandon** [comment]
Is that because you install two hooks, one for buildkite and one for coming-gate? We currently have removed our buildkite hook in favor of only using ci-gate. It seemed more secure that way as toggling third party PRs is just a checkbox in Buildkite. We felt like there’s additional layers of security on a larger team without the default hook installed.

**Comment by mvines** [comment]
Yeah I've been using two hooks with the buildkite hook only set to receive Pushes out of laziness.  This is a nice alternative though. 

I'd prefer to make that hard coded `if (ref !== 'refs/heads/master') ...` configurable, in my usage I do want to build non-master pushes.

**Comment by KevinGrandon** [comment]
> I'd prefer to make that hard coded `if (ref !== 'refs/heads/master') ...` configurable, in my usage I do want to build non-master pushes.

Yeah, ideally this could query buildkite for the settings in the UI, or perhaps even an environment variable with a list of branches. Will work on this a bit more first.

**Pull request closed without merging**
